### ISSUE TITLE
PRIORITY 1: Angela Fling - oops an error has occurred - i've sent out an email to these clients

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#100]
click on COMPARISONS - error msg screen.  
comparison - new gives this error
Server Error in '/' Application.

Object reference not set to an instance of an object. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 1212:                    catch
Line 1213:                    {
Line 1214:                        var termLength = topTariff.Descendants("term-length").FirstOrDefault().Value;
Line 1215:                        var tariffStartDate = Convert.ToDateTime(er.ComparisonDate);
Line 1216:                        var tariffEndDate =

Source File: c:\inetpub\wwwroot\App_Code\BLL\Clients.cs    Line: 1214 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Clients.Client.BuildBatchComparisons(String supplyType, ClientType ct, Boolean standardTariff, Boolean doubleToSingleSupplySwitch) in c:\inetpub\wwwroot\App_Code\BLL\Clients.cs:1214
   Clients.Client.BuildBatchComparisons(String supplyType, ClientType ct, Boolean standardTariff) in c:\inetpub\wwwroot\App_Code\BLL\Clients.cs:1032
   Clients.Client.BuildBatchComparisons(String supplyType, ClientType ct) in c:\inetpub\wwwroot\App_Code\BLL\Clients.cs:1027
   Admin_BatchTariffComparison.LoadSavings() in c:\inetpub\wwwroot\Admin\BatchTariffComparison.aspx.cs:459
   Admin_BatchTariffComparison.LoadClientDetails() in c:\inetpub\wwwroot\Admin\BatchTariffComparison.aspx.cs:249
   Admin_BatchTariffComparison.Page_Load(Object sender, EventArgs e) in c:\inetpub\wwwroot\Admin\BatchTariffComparison.aspx.cs:26
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +24
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +41
   System.Web.UI.Control.OnLoad(EventArgs e) +131
   System.Web.UI.Control.LoadRecursive() +11142014
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2427

**Comment by iddmaxwell** [comment]
I changed the tariff  and then set it back to BG standard and the error has gone now.

**Comment by Will-Newton** [comment]
Need to see the data that causes this, so will wait until it happens again.

**Comment by iddmaxwell** [comment]
Example is Steve Bryant.

**Comment by Will-Newton** [comment]
fixed
