### ISSUE TITLE
PRIORITY 2: Many tariffs are incorrectly marked as variable so don't come up as the top fixed tariff. 

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#101]
If it's easier, just remove the panel "top fixed tariff" as it's misleading.
Example is Affect Energy which is marked as fixed to May 2018 but thetop fixed tariff is shown incorrectly as Sainsbury's Energy
https://optimisebills.com/Account/ClientComparison.aspx?U=c107dda3-4ba9-4718-946f-e8c6e3c38a25&StandardTariff=True&E=824261

**Comment by Will-Newton** [comment]
Isn't it the case that they're fixed for a certain period of time so technically it's correct? I don't think the logic is incorrect - it just run off an 'is-capped' true/false field on the api. Or is there some other logic we can use?

**Comment by iddmaxwell** [comment]
undecided
