### ISSUE TITLE
PRIORITY 1: tariff manager: cannot select 2018 tariffs.  Supplier dropdowns don't match energy record dropdowns

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#122]
For example, Affect Energy is an option on the tariff manager.  But is not an option in the energy record editor.

**Comment by Will-Newton** [comment]
I've added 2018 to the date filter and added Affect Energy to the tariff manager.

**Comment by iddmaxwell** [comment]
2019 cannot be selected.  Can this be updated automatically?

**Comment by iddmaxwell** [comment]
fixed - Will
