### ISSUE TITLE
PRIORITY 1: enhance security

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#124]
Remove users not in use.
Update password for my login as requested by text.
Any other measures you feel would be important?

**Comment by Will-Newton** [comment]
I've updated the paasword. What criteria is needed for deleting users?

**Comment by iddmaxwell** [comment]
What users are set up with access?  We should remove any not in active use - i.e. other than me and you.

**Comment by iddmaxwell** [comment]
have you removed all other users? 
If not, can we leave one and let me know the password for it.  Or set password to the value I will text you after you reply to this

**Comment by iddmaxwell** [comment]
Claire and Jamie added as users
