### ISSUE TITLE
PRIORITY 1: registration taking a very long time to respond. No response to client. 

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#125]
Added a new client via the registration page.  Taking over a minute so far to respond after pressing "see how much I could save". 
The web site was responding quicker after the server was restarted on Friday. 
It's been about 10 minutes so far with no response.  I checked from my phone and the record has been created on the web site.  Not sure why it's not coming back with a message saying it's done.

**Comment by Will-Newton** [comment]
I've rebooted the server. There was updates waiting to be installed. Will look further into the code if it's still slow.

**Comment by iddmaxwell** [comment]
It isn't responding at all from a client point of view. Just stuck on the screen 'to find out what you could save...' 
However it appears that a record has been created - alert email has been sent - and I think the record has been created. However the signin screen was extremely slow to respond so I  can check.  I had to close the registration window and eventually was able to log in.
So overall it's not working fully.

**Comment by iddmaxwell** [comment]
I then received an alert email which should not have appeared: 

Client Re-Registration: Merged
Iantest test : iantest64@srpi.co.uk
calculation complete
Current: npower Standard : npower Standard
New top: Avro Energy Simple and Glow
New top fixed: Extra Energy Fresh Fixed Price Dec 2017 v1

**Comment by Will-Newton** [comment]
Made some performance improvements
