### ISSUE TITLE
PRIORITY 1: Calculate button does not work on Anita Kelso's tariff record - or other records?

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#128]
https://optimisebills.com/Admin/EnergyRecordEditor.aspx?RecordNum=KEL005-03T
Updated kwh and pressed calculate.  No response and no error message. 
Sounds the same as errors I have reported before with calculate not working. But all rate fields are filled in.
Also record won't save when I press 'update'. 

This record does calculate
https://optimisebills.com/Admin/EnergyRecordEditor.aspx?RecordNum=CRO004-01T

**Comment by Will-Newton** [comment]
It's working for me. Which fields are you updating and what are the new values?

**Comment by Will-Newton** [comment]
![image](https://user-images.githubusercontent.com/12527418/36699954-43d6130a-1b46-11e8-8987-69bd76e3aeaa.png)

**Comment by Will-Newton** [comment]
There's html in the terms fields that triggers security. Remove that and it'll load.
