### ISSUE TITLE
PRIORITY 1: query security settings

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#134]
trying to connect to optimisebills.com/client manager 2
message: 

  | Can’t connect securely to this page                         This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
-- | --

**Comment by Will-Newton** [comment]
Which device/browser are you using to see this message?

**Comment by iddmaxwell** [comment]
Comodo security certificate should resolve.
