### ISSUE TITLE
PRIORITY 1: Add new suppliers - Gulf Gas & Power

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#135]
Also add Utility Point's logo to the client page.

**Comment by Will-Newton** [comment]
I've added the suppliers. Is there somewhere to get the utility point logo from?

**Comment by iddmaxwell** [comment]
try energyhelpline.com
Also need to add Bulb energy.

**Comment by iddmaxwell** [comment]
Is there a way of scraping the rates from one of these websites as we used to with UK power?

**Comment by iddmaxwell** [comment]
Add Solarplicity logo to client energy record screen

**Comment by iddmaxwell** [comment]
Utility Point is not available to select as a supplier under COMPARISON OLD

**Comment by iddmaxwell** [comment]
So energy needs to be added as a supplier

**Comment by iddmaxwell** [comment]
Utility Point is not available on the 'comparison-old' screen.

**Comment by iddmaxwell** [comment]
daligas is not available on Tariff table dropdown

**Comment by iddmaxwell** [comment]
New suppliers need to be added to Registration page - plus energy record editor, tariff manager, comparison old page.

**Comment by iddmaxwell** [comment]
Add ESB to all screens.

**Comment by iddmaxwell** [comment]
add Igloo to list of suppliers.

**Comment by iddmaxwell** [comment]
add first:utility to suppliers in Comparison_Old

**Comment by iddmaxwell** [comment]
add Utility Point to comparison_old and any other new suppliers

**Comment by iddmaxwell** [comment]
add eversmart logo to CM2 screen

**Comment by iddmaxwell** [comment]
add ESB to list of suppliers

**Comment by iddmaxwell** [comment]
cannot update tariff with Pure Planet in energy record or comparison old

**Comment by iddmaxwell** [comment]
Add Leccy to list of suppliers

**Comment by iddmaxwell** [comment]
Powershop is not available on Comparison_Old but is in Tariff manager. 
all suppleirs should be in
Tariff manager
energy record
registration page
comparison old

**Comment by iddmaxwell** [comment]
supplier logos missing (or text intead) on CM2 for
Eversmart
Pure Planet

**Comment by iddmaxwell** [comment]
Suppliers required Tariff table, energy record, reg page, comp old, logo
Bulb    N
daligas Y
ESB  Y
Eversmart  Y
first:utility  Y
Igloo  Y
People's Energy  N
Pure Planet  Y
Powershop  Y
So Energy
Solarplicity  Y
Utility Point  Y

**Comment by iddmaxwell** [comment]
suppliers still missing from tariff table etc e.g. Peoples Energy - see above

**Comment by iddmaxwell** [comment]
OUtfox the Market to be added

**Comment by iddmaxwell** [comment]
Symbio also still missing

**Comment by iddmaxwell** [comment]
to test

**Comment by iddmaxwell** [comment]
Please add 
Simplicity Energy

NB Symbio does not match on MUG load - need to select manually
Also ScottishPower does not match -need to select manually

**Comment by iddmaxwell** [comment]
logos missing
Symbio
Powershop

**Comment by iddmaxwell** [comment]
Simplicity Energy not there in tariff manager at least

**Comment by iddmaxwell** [comment]
Octopus Energy missing from Tariff Manager at least
