### ISSUE TITLE
PRIORITY 1: email sending error.

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#166]
tried sending an email "switch confirmation" to Ian MacDonald - 421 Lower Hall St.

Got an error: - could this be related to field changes you are making or something else? 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

A potentially dangerous Request.Form value was detected from the client (ctl00$MainContent$EmailHtmlEditor="<div style="font-siz...").
Description: ASP.NET has detected data in the request that is potentially dangerous because it might include HTML markup or script. The data might represent an attempt to compromise the security of your application, such as a cross-site scripting attack. If this type of input is appropriate in your application, you can include code in a web page to explicitly allow it. For more information, see http://go.microsoft.com/fwlink/?LinkID=212874.

**Comment by Will-Newton** [comment]
resolved
