### ISSUE TITLE
'load' button on CM2 causes 'data invalid' for lots of clients

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#25]
Examples are: 
Rob Binns.
for some reason we have clients whose tariff does not have a valid UK Power supplier id. maybe because it's blank, or because it was copied from another tariff manually.
Keith Fling
on GB Energy premium.  This has a UK Power id on the tariff record: 3802.  So looks ok.
Where is the UK Power supplier id held? I can't see it on the energy record. Is it only on the tariff record? 
I think this is why lots of the clients generate 'data invalid' on clicking the 'load' button. But there could be other reasons.
We need these clients' records fixing.  
can we have a script that goes through current clients one by one, tries to generate a  UK POwer link for them, and fixes them if it doesn't work? 
The script will need to trap the various reasons for failure and address each one. 
So invalid UK POwer supplier id: 
find valid list of UK POwer supplier ids from the API
match supplier name against the list 
update the tariff table with the valid UK POwer supplier id
recheck the UK Power link load process to make sure it works this time.
store the result in UK Power link 2 (to avoid overwriting in case the script doesn't work). 
other reasons for error
**payment method not set correctly:** 
choose a valid payment method from the list available and use that.  Default to Direct Debit if there is no other.  

I think this is now a bug.  I cannot find a client that the button works for!  Something must have changed at the UK Power end I guess.

**Comment by Will-Newton** [comment]
Main issue is that ukpower have changed the required fields.

**Comment by Will-Newton** [comment]
Ukpower must have changed something at their end that prevents us from generating links this way. I've tried changing everything to precisely match a normal usage submission on their website and it's still saying there's a problem.

**Comment by iddmaxwell** [comment]
Is there another way round it? Creating a link dynamically on request?

**Comment by Will-Newton** [comment]
Ukpower must have changed something at their end that prevents us from generating links this way. I've tried changing everything to precisely match a normal usage submission on their website and it's still saying there's a problem.

**Comment by Will-Newton** [comment]
We are creating it dynamically on request. There's no way of using this method any more.

**Comment by iddmaxwell** [comment]
We need to find a way somehow. It's a manual process for me now. If the user goes through the screens manually it generates a link. Is that something that can be used?
Or can we ask uk power? 
Or are you saying the only option is to use the API? How long to set this up fully?

**Comment by Will-Newton** [comment]
Which screens generate a link?

Ukpower would probably say to use the API.

Set up the uk power api fully? Its part of the new website. Need to be committed to that to get it up and running but I'm mainly on these old website issues at the moment.

**Comment by iddmaxwell** [comment]
go to https://www.ukpower.co.uk/ 
enter postcode & click 'compare prices'
click on type (e.g. dual fuel), 
'yes' for both fuels same supplier (e.g.), 
current supplier, 
drop down list of tariffs, 
current payment method dropdown, 
click Economy 7 Y or N (if applicable),
click spend £ or usage kwh
enter kwh for gas and electricity (if both applicable)
click 'view results'
next screen shows a page such as https://www.ukpower.co.uk/home_energy/compare/dual/HTEBT7HS

The actual options above vary according to what is clicked/entered previously. So elec only, economy 7, different gas/electricity suppliers, etc. could change the options shown.

**Comment by Will-Newton** [comment]
What do I need to do with this?

**Comment by iddmaxwell** [comment]
this answers your question "which screens generate a link?"
if a user can go through the sequence to get a UK Power link, is it possible to emulate that in some way?

**Comment by Will-Newton** [comment]
We were but they block traffic that isnt from their site now.

**Comment by iddmaxwell** [comment]
API process now in place so close.
