### ISSUE TITLE
Standard tariffs are not being set up with 'Vstd' flag

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#36]
Result is that standard tariff cannot be identified when client clicks on the email link e.g. from "client comparison - Standard tariff" email.
This creates an error when the client clicks that email.
A separate issue is that the UK Power link is not being created, which also needs fixing to resolve this fully.

**Comment by Will-Newton** [comment]
I've updated the flags field on the standard tariffs to include 'Vstd' and added it to the load script

**Comment by iddmaxwell** [comment]
Lots of clients getting error messages, such as: 
Wendy Truppin-Brown 
Failed to load standard tariff, tariff missing
15-Nov-2016 19:21
Also the system seems to be going very slowly.

**Comment by iddmaxwell** [comment]
tariff load is no longer in use.  Close
