### ISSUE TITLE
Tariffs missing from new script

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#38]
e.g. Flow Winter Warmer.
I can see it in the csv file but most records have an area of 'NULL' which I think means that it doesn't get loaded to the tariff table.
It's odd - the only areas loaded for Dual Fuel Economy 7 are: 
Manweb
Norweb
Midlands
Unknown
Could it be that these are the last three in the list - areas 13, 14, 15?  
haven't checked other tariffs fully yet.  
gas only has the same
elec only has Norweb, Midlands, Unknown.

**Comment by Will-Newton** [comment]
Area is an obsolete field. Replaced by postcodeareaid.

Looks like the tariff was added to ukpower midway through the load process.

**Comment by iddmaxwell** [comment]
OK.  When can they be added?  
Why are there some tariffs with area "unknown"?

**Comment by Will-Newton** [comment]
They'll be added next time the load process runs.


I had to add the unknown area cant remember why, users or tariffs didnt have an area probably. They dont get copied across will stop it loading tariffs with that area id.






On Wed, Oct 5, 2016 at 3:52 PM +0100, "Ian" <notifications@github.com> wrote:












OK.  When can they be added?


Why are there some tariffs with area "unknown"?

**Comment by iddmaxwell** [comment]
This tariff is still not loaded. I thought there was a process operating every 5 days?

**Comment by Will-Newton** [comment]
5 days isnt long enough. It needs 7. And that issue yesterday from the website took it down. So its going to be 6 days still before they're all there.






On Thu, Oct 13, 2016 at 4:58 PM +0100, "Ian" <notifications@github.com> wrote:












This tariff is still not loaded. I thought there was a process operating every 5 days?

**Comment by iddmaxwell** [comment]
Can I see the output from the process that uploads new tariffs so I know what's happening?
Can you produce a list of what has been set to 'in use' rather than 'active' too?

**Comment by iddmaxwell** [comment]
As per previous comment, how do I know the process is running?  Also as requested separately can we look at how to improve the run time?  can you send me the code?

**Comment by iddmaxwell** [comment]
I've looked at the tariff table at various dates and the most recent is 4th November, so nothing has been added for the past 11 days.  I thought it was supposed to run at least weekly?  
It means the OB web site even further behind UK Power than it needs to be. can you restart the script asap?

**Comment by iddmaxwell** [comment]
When is the tariff upload running?  Is it automatic and will it automatically update the tariff table? If so when?

**Comment by Will-Newton** [comment]
I'm going to look at populating the comparisons on the current website via the api. It might not be as much work as I initially thought and would solve a lot of the api loading issues.






On Fri, Nov 25, 2016 at 11:54 AM +0000, "Ian" <notifications@github.com> wrote:












When is the tariff upload running?  Is it automatic and will it automatically update the tariff table? If so when?

**Comment by iddmaxwell** [comment]
OK when is this going to happen? are you going to finish sorting the email first?

**Comment by Will-Newton** [comment]
Which template has a link that works on your iphone? Cant do anything about the phone number on ukpower. Will be looking at the api current site integration on sunday.






On Fri, Nov 25, 2016 at 12:02 PM +0000, "Ian" <notifications@github.com> wrote:












OK when is this going to happen? are you going to finish sorting the email first?

**Comment by iddmaxwell** [comment]
Can you refresh the tariff list?  Last time was 19/11.

**Comment by iddmaxwell** [comment]
Tariff list needs refreshing.  It's now quite out of date.  Can you do this weekly until the new web site is working?

**Comment by iddmaxwell** [comment]
Latest tariff list has not removed some that were removed some time ago. 
e.g. isupplyenergy ifix Aug18 is still in our table.  When did the process to clear out old tariffs last run?

**Comment by iddmaxwell** [comment]
Looks like the latest tariff load was over a month ago. We need to keep the tariffs up to date until the new web site is working.  I thought it was set to automatic? 
Prices are going up and people are opting for tariffs on our web site that are no longer available.
Please update the list asap.

**Comment by iddmaxwell** [comment]
Facility no longer in use.  Therefore close
