### ISSUE TITLE
Objectives for the new platform

### ISSUE THREAD

**Issue by Will-Newton** [iddmaxwell/optimisebills#40]
I want to make communications a key feature. Emails and tracking them and push notifications via the app.

And then the content should be links to sites that genera

**Comment by Will-Newton** [comment]
te revenue.

The basic process flow...
- determine the markets where a client is spending a lot of money via the OB app/online.
- Provide them the link to improve their spending.
- Receive commission when they click through the link and spend.

With the primary focus on finding new business that doesnt require any human intervention.

Automate periodic notifications and automate the link generation via apis and scraping tools.

Spend more time finding new ways for people to save, building an online community and providing good market information and less time managing client data/tariff data.

Is there a problem with this in that the majority of OB clients can't do the clicking through themselves and require lots of assistance? How much time do you have to spend per client? Does it vary a lot?

**Comment by iddmaxwell** [comment]
What is the status of the script to issue an email to clients whose tariffs are coming to an end?  We spoke about this a couple of weeks ago.  
We need clients - tariffs ending - with an email showing: 
what tariff we think they are on
when the tariff ends
what their current usage is in kwh/year and in £/month

**Comment by Will-Newton** [comment]
Its around 40% complete. Aiming to have it ready to look at on Wednesday.






On Fri, Nov 11, 2016 at 3:50 PM +0000, "Ian" <notifications@github.com> wrote:












What is the status of the script to issue an email to clients whose tariffs are coming to an end?  We spoke about this a couple of weeks ago.


We need clients - tariffs ending - with an email showing: 

what tariff we think they are on

when the tariff ends

what their current usage is in kwh/year and in £/month

**Comment by iddmaxwell** [comment]
Any update on this?  We need to get off the current web site as soon as we can. It's slow to manage and confusing for clients.

**Comment by iddmaxwell** [comment]
Superseded by other issues so close.
