### ISSUE TITLE
Process deadlock

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#44]
as per email, this is the error screen that the client got (Brenda Green)

Server Error in '/' Application. 
________________________________________
Transaction (Process ID 70) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Transaction (Process ID 70) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Source Error: 
Line 91:             conn.Open();
Line 92:             SqlDataReader reader = comm.ExecuteReader(CommandBehavior.CloseConnection);
Line 93:             reader.Read();
Line 94:             if (reader.HasRows)
Line 95:             {

Source File: c:\inetpub\wwwroot\App_Code\DAL\TariffsDAL.cs    Line: 93 

Stack Trace: 
[SqlException (0x80131904): Transaction (Process ID 70) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection) +212
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj) +245
   System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj) +2843
   System.Data.SqlClient.SqlDataReader.HasMoreRows() +266
   System.Data.SqlClient.SqlDataReader.ReadInternal(Boolean setTimeout) +278
   OptimiseBills.DAL.TariffsDAL.GetTariffFromDate(String tariffSupplier, String tariffName) in c:\inetpub\wwwroot\App_Code\DAL\TariffsDAL.cs:93
   MiscUtil.Tariffs.GetTariffFromDate(String tariffSupplier, String tariffName) in c:\inetpub\wwwroot\App_Code\BLL\MiscUtil.cs:270
   EnergyRecords.EnergyRecord.CalculateTariffStatus(RecordSection rSection) in c:\inetpub\wwwroot\App_Code\BLL\EnergyRecords.cs:1748
   EnergyRecords.ComparisonRecord..ctor(EnergyRecord CTR, Int32 tariffID) in c:\inetpub\wwwroot\App_Code\BLL\EnergyRecords.cs:1933
   Clients.Client.BuildBatchComparisons(String supplyType, ClientType ct, Boolean standardTariff, Boolean doubleToSingleSupplySwitch) in c:\inetpub\wwwroot\App_Code\BLL\Clients.cs:967
   Clients.Client.BuildBatchComparisons(String supplyType, ClientType ct, Boolean standardTariff) in c:\inetpub\wwwroot\App_Code\BLL\Clients.cs:928
   Account_LinkReport.Page_Load(Object sender, EventArgs e) in c:\inetpub\wwwroot\Account\LinkReport.aspx.cs:171
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +42
   System.Web.UI.Control.OnLoad(EventArgs e) +132
   System.Web.UI.Control.LoadRecursive() +11142047
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2428

________________________________________
Version Information: Microsoft .NET Framework Version:2.0.50727.5485; ASP.NET Version:2.0.50727.5491

**Comment by Will-Newton** [comment]
Think this is resolved by using the api
