### ISSUE TITLE
URGENT IF QUICK TO FIX - Failed to load standard tariff, tariff missing 

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#45]
Failed to load standard tariff, tariff missing
Current tariff: First Utility iSave Fixed December 2016 v5

This is affecting lots of clients - don't know why.  Some wrongly think that there is no saving and so are not inclined to switch.  Also the savings are completely different from the UK Power link.

can you fix this quickly ? It should work

**Comment by Will-Newton** [comment]
What is the standard tariff for first utility?

**Comment by iddmaxwell** [comment]
Is anything happening on this?

**Comment by Will-Newton** [comment]
I set the standard flag for fu tariffs but it doesnt seem to have worked. Will take a look this evening at why its not working.


Get Outlook for Android






On Tue, Nov 22, 2016 at 5:14 PM +0000, "Ian" <notifications@github.com> wrote:












Is anything happening on this?
