### ISSUE TITLE
New server comparison process issues

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#56]
1. Philip McConville. Click COMPARISONS. "An error occurred."  

On Max Howard's record: 
2. calculation of cost of current tariff is incorrect. Shows £477 and it should be £288. So the savings are incorrect too.   Still not working correctly.  Expected cost is correct but the saving by each tariff is not.  Seems to be comparing to the price prior to changing the client's current tariff. Not sure where this would be held!    CALCULATION INCORRECT FOR IAN TEST70.  WILL HAVE TO TRY OTHERS TOO.  ALSO INCORRECT FOR MAX HOWARD - SEE COMMENT BELOW.
3. there is a new collapsible box "tariff details". It repeats almost all the tariff terms and does not show a valid unit rate or standing charge (which are the only items that could be useful), showing both as 0.  So we can remove the tariff terms from this box and check the rates are correctly displayed. BOX REMOVED 
4. text "there is no change..." Should be "There is no change to..."  TEXT NOW REMOVED.   
5. text "But click here if you have any questions" has no hyperlink.  Also it would be extremely small compared to the buttons.  The text needs to be connected obviously to a button "Please contact me about my switch." or the button at the bottom which doesn't look like a button because of the colour.  Looks a bit messy just now.   TEXT REMOVED BUT COLOUR OF BUTTON AT THE BOTTOM IS UNCHANGED.    
6. text "click here to go to our switching partner web site where..."  TEXT NO LONGER PRESENT. 
Remove text and change "Next" button to "Go to request switch"  BUTTON NOT UPDATED. 
CLICKING ON THIS BUTTON NEXT/GO TO REQUEST SWITCH SHOULD TAKE YOU TO THE SWITCHING APPLICATION FORM, NOT THE TARIFF MORE INFO SCREEN.

**Comment by iddmaxwell** [comment]
Point 2.  Looks as if the tariff passed across to the API is incorrect.  the page "Your details" on UK Power is set to British Gas Standard tariff Dual Fuel, when the client is on Flow Winter Warmer April 2017 Gas Only.

**Comment by iddmaxwell** [comment]
Switching to a tariff not available on UK Power. 
1. Current address and billing address fields are too short
2. Email address is missing. 
3. Smart meter - default to No rather than Yes
4. Direct debit details.  Headings are not quite right
Name in which account is held [can we default to Initial and Surname, e.g. M Howard]
Account Number
Sort Code
Preferred Payment Day.  Add note "this will be requested if there is an option"
5. Previous addresses. Can we show only if the time at current address is less than 3 years? 
Rather than "from date" and "to date" ask "length of time at this address" in years and months.   Total needs to add up to 3 years.
6. All the fields could fit on one page with some rearranging.  E.g. title, first name, surname on the left, telephone numbers on the right.   Similarly with bank account details. 
7. DOB - bring forward from client record.  Youngest dob seems to be from 1994?  Should allow later years than this.  
8. text to change on page "Thank you for confirming your switch request"
We will check the information you have provided and use this to request your switch. 
You should then receive a confirmation email from your new supplier in the next day or so.  You will have 14 days to change your mind.  
If you do want to cancel please contact your new supplier and also let us know by calling 0345 130 3858 or sending an email to info@optimisebills.com.  
9.  Where are the switch details stored?

**Comment by iddmaxwell** [comment]
on the telephone (day), (evening) and (mobile) fields, show only the first 11 digits. / 12 characters including spaces. sometimes there is text afterwards

**Comment by iddmaxwell** [comment]
2nd thoughts on the data on the switching page: 
- leave title, first name, last name blank. validate that they've been entered. 
- leave telephone number fields blank for the client to complete.  validate first one to make sure it's been entered.
- pre-fill Address fields if available but require Address line 1 to be entered if not already completed.  
- leave dob blank.  for the client to complete as the others above. 

I'm just conscious that we haven't requested the client log in; this is just clicking on an email. so it's an information security issue.

**Comment by iddmaxwell** [comment]
I tried requesting a switch to Bristol Energy for Max Howard (via OB switching page.)
it's not clear where the data has been stored.  I've looked in the diary items and on the switching page and the data is not there. 
Saving calculation is incorrect as noted above. On the comparison page it shows current cost (correctly) recalculated from the energy record.  However the saving shown lower down the screen is incorrect. It seems to be using the comparison record instead of the Client's Tariff record.  
Another issue is that I cannot get the current price on the comparison record to recalculate. It's stuck at 344.65 for Max Howard.  Is this another issue?

**Comment by Will-Newton** [comment]
I will look again at these but the idea here was just to change the comparisons to use the api to save keeping the tariff table up to date. I don't really want to get into UI changes on the old website. Might be better just to tell people we'll be in touch via phone if the tariff isn't on UK Power and get back to the new website? 

I don't think the API is using a comparison record instead. We don't have the tariff Id for this one so it's just passing the other stuff to the api: gas only, flow energy, 1000Kwh and the api must make assumptions on the tariff.

On the new comparison record? It's not pulling back the rates from the api. Do we need them? If we're just using the api for comparisons, do we need the rates?

**Comment by Will-Newton** [comment]
I've added the security changes. The switch details are visible on the switching tab in CM3/CM2.

**Comment by Will-Newton** [comment]
I made quite a few of the changes to the link report page that it looks like weren't visible when you tested. Were you in the /test/ directory?

**Comment by Will-Newton** [comment]
I think this is resolved
