### ISSUE TITLE
Other Remote Desktop issues

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#59]
Client: Beth Ellison.  
"Oops an error has occurred."
I changed the tariff manually to a new one and the same error happened. 

It says we've logged and will investigate it.  Is that true? How is the error logged? 
Text needs to change to 0345 130 3858.

**Comment by Will-Newton** [comment]
Probably resolved

**Comment by iddmaxwell** [comment]
unable to test as I don't know what causes the error.
