### ISSUE TITLE
PRIORITY 1. Update registration page to refer to API list of tariffs rather than our tariff table

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#63]
priority 1 TO DO 4/3/17
update registration page to use API list of tariffs
priority 2
tba
priority 3- PARK FOR NOW
load our tariff table with all rates and UK Power ids for all active and available tariffs

**Comment by iddmaxwell** [comment]
in progress.

**Comment by Will-Newton** [comment]
done except for parked item
