### ISSUE TITLE
PRIORITY 1. CM2 cannot change tariff from Iresa to another in the comparison record. Still causing problems.

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#64]
**priority 1.**
This one is preventing me from getting clients' records correct.

on Thomas Speed's record. Created a new comparison record. Need to amend to Avro tariff and then click current, but the tariff won't change in the energy record.  
If I go to a different comparison record it does work.

**Comment by Will-Newton** [comment]
We need to switch over to the new api tariff load to fix this one. Have you been able to test that at all?

**Comment by iddmaxwell** [comment]
on the pilot site, the new record I created - Katharinetest Maxwelltest.  attempt to view a comparison record - tonik supplier - causes a 500 internal server error.  So it's not working it seems.
I also clicked on the current tariff Flow Connect 6.  changed supplier to Iresa Energy but it's not displaying the other tariffs.  So that's not working.
Is that what you mean? 
You can test it yourself in the same way.  Let me know when it's working and worth looking at again.

**Comment by Will-Newton** [comment]
I need uto update a list of supplier ids for the energy record, so new suppliers won't work yet.

**Comment by iddmaxwell** [comment]
I'm a bit confused. Surely we need new suppliers to work.  Presumably you knew this already?  Not sure what I'm supposed to test if not this.

**Comment by Will-Newton** [comment]
Just test it works for an existing supplier. I will update the list of suppliers when it's ready to go live.

**Comment by Will-Newton** [comment]
(didnt want to update the list of suppliers, then need to update it again when I was putting it live)

**Comment by iddmaxwell** [comment]
OK tried EDF and it appears to work ok.
however, probably an old issue but the 'terms' and 'flag' and 'tariff code' are not being updated correctly.

**Comment by Will-Newton** [comment]
We can't update any other fields because that data is only on the quotes feed.

**Comment by Will-Newton** [comment]
All supplier ids loaded via api now on pilot

**Comment by iddmaxwell** [comment]
I'm trying to update the supplier/tariff in live and it is not working

**Comment by iddmaxwell** [comment]
Still an issue.

**Comment by iddmaxwell** [comment]
This issue is preventing me from making any changes to clients' energy records if they have been loaded through the API.  It's a major problem.

**Comment by iddmaxwell** [comment]
Can we get this fixed? I assume it is affected bythe discussion we had last week on pulling additional information through for our energy records.  
The problem with clients who have tariffs with blanks in the energy record fields will escalate as their tariffs disappear from the quotes feed.  Is there any other way to get these rates?  They are present on the UK Power version of the quotes.

**Comment by iddmaxwell** [comment]
I see that exit charges are now being pulled through although not yet the rates.  When will you have this done?

**Comment by Will-Newton** [comment]
The html tags in the terms were causing the problem. Code isn't allowed in these fields by default as a security measure. I've changed it to allow html tags on this page so should be working now.
