### ISSUE TITLE
PRIORITY 2 Comparison New is not working - shows 'error' inplace of supplier logos and no tariff names

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#65]
PRIORITY 3.  now 2.  this is causing some issues.
Working on Neil Simpson. Click Comparison New.  Next step to click on one tariff to create a comparison record.  But I can't see which one to click on.  (have to choose a random one and hope it's correct.)

**Comment by Will-Newton** [comment]
resolved somewhere else
