### ISSUE TITLE
PRIORITY 3 IF ADMIN ONLY AFFECTED. Diary item "Comparisons viewed" is not showing the tariff

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#66]
Priority 3 if this is not visible to clients. 
e.g. (for Robert Stuttaford)
Current Supply: first:utility iSave Everyday (v3) for a total of £2,624. The best saving available was £815 on   and the best saving on a fixed price tariff available was £751 on  .

As long as the client sees the correct savings and tariff it's not critical.

**Comment by Will-Newton** [comment]
fixed
