### ISSUE TITLE
PRIORITY 2: Switch Button shows 'switch now' instead of 'request my switch is done for me'

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#69]
PRIORITY 2
Eric Smith
click Comparisons
choose Avro (not available on UK Power)
button says 'switch now'
next screen presented correctly "Switch Details - Avro Energy"

I've noticed that on a Scottish Power tariff - available on UK Power - the button shows
'request my switch is done for me'.
You mentioned last night 16/3 that there is separate code for clients vs non clients.  Not sure why it's arisen but part of simplification should be to use the same code for the same situation. Otherwise it needs updating in every occurrence which can of course lead to errors. 
e.g. the code to display 'do you want to sign up' would ideally be separate from the rest of the switch page details. I understand it's all part of the same page at the moment.  
We have a similar situation with the Comparisons button and the Comparison-New link.  Perhaps we can discuss.

**Comment by Will-Newton** [comment]
Client not signed up buttons

**Comment by Will-Newton** [comment]
fixed on pilot
