### ISSUE TITLE
priority 2: Neil Bickley.  Cannot update kwh values on energy record

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#70]
No error is shown. 
Tried the console and it shows 'unknown error' 500 including: 
SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.

may be connected with separate issue - cannot update tariff on energy record if there are no rates loaded. (newer tariffs from API)

**Comment by Will-Newton** [comment]
Will be fixed in next update from pilot
