### ISSUE TITLE
PRIORITY 3. UK Power link generation failure: Data invalid

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#73]
This diary item is created for lots of clients. Maybe every time someone clicks on 'Switch Now'.
There's no obvious reason why because the UK Power link is created.
At the same time, we get the diary item 'switch now'.  
It would be preferable to create only one diary item per click because it takes extra time removing all the redundant ones.

**Comment by Will-Newton** [comment]
I think this is an error in the link generation for a certain scenario and is fixed in pilot
