### ISSUE TITLE
PRIORITY 2: Cannot edit client energy record

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#77]
Paul Matthews MAT001
Click on View/Edit against tariff record. Error screen: 
The remote server returned an error: (500) Internal Server Error. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.

Source Error: 

Line 395:            var elecTariffUrl = "http://services.ukpower.co.uk/home_energy/api/tariffs.xml?api_key=8B34-7EDA-E529-B25D-8755&limit=0" + tariffQuery;
Line 396:
Line 397:            elecTariffDoc = XDocument.Load(elecTariffUrl);
Line 398:            var topTariffList = elecTariffDoc.Descendants("tariffs").ToList().FirstOrDefault();
Line 399:            var tariffs = topTariffList.Descendants("tariff").ToList();

Source File: c:\inetpub\wwwroot\Admin\EnergyRecordEditor.aspx.cs    Line: 397 

Stack Trace: 

[WebException: The remote server returned an error: (500) Internal Server Error.]
   System.Net.HttpWebRequest.GetResponse() +1126
   System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials) +86
   System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) +65
   System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext) +200
   System.Xml.Linq.XDocument.Load(String uri, LoadOptions options) +48
   EnergyRecordManager.GasDropDownChange(DropDownList supplier, DropDownList NewTariff, DropDownList SType, DropDownList Area) in c:\inetpub\wwwroot\Admin\EnergyRecordEditor.aspx.cs:397
   EnergyRecordManager.Page_Load(Object sender, EventArgs e) in c:\inetpub\wwwroot\Admin\EnergyRecordEditor.aspx.cs:61
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +42
   System.Web.UI.Control.OnLoad(EventArgs e) +132
   System.Web.UI.Control.LoadRecursive() +11142047
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2428

**Comment by Will-Newton** [comment]
Fixed
