### ISSUE TITLE
UK Power URLs

### ISSUE THREAD

**Issue by jamiemax** [iddmaxwell/optimisebills#8]
At the moment, the site generates URLs that look like this:

https://www.ukpower.co.uk/home_energy/compare/dual/CXAH3Y26?r=srpi

This takes you to a page where you can only see the tariffs available through UK Power, and you have to click a link at the top to see the full list

Is there any reason we couldn't have a link like this?:

https://www.ukpower.co.uk/home_energy/compare/dual/CXAH3Y26?compare_type=all_available&r=srpi

This would show the whole list of tariffs by defaul

**Comment by iddmaxwell** [comment]
superseded by use of API
