### ISSUE TITLE
PRIORITY 1: Need to correct email in order to send out to non-clients

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#84]
Hi Will
I’m trying to update this email to use to send out to non-clients.
I have two problems: 
1.	The link is shortened for some reason to http://../Account/Usage.aspx which doesn’t resolve
2.	I included the word ‘postcode’ in the template but it’s being converted to the client postcode on file.

Can you update the template/advise me how to?  

Thanks 
Ian

Ian Maxwell
M: +44 (0)7866 767630

From: OptimiseBills 
Sent: 10 April 2017 15:11
To: test62@srpi.co.uk
Subject: Quotes from existing OptimiseBills customers

 
Dear Ian
You are receiving this because you previously enquired about saving money on energy through OptimiseBills.
These are some quotes from existing clients describing repayments of several hundred pounds, as a result of challenges we made with energy suppliers:  
“Ian helped unravel a problem with my energy bills that went back four years.  He got the supplier to put me on the correct tariff and instead of being £219 in debit I was now £713 in credit - an improvement of £932!  And I got a goodwill payment on top.  Thank you OptimiseBills!”  Ms B. Hughes, Liverpool
"I was persuaded over the phone by my energy supplier to change tariff to a longer fixed rate.  OptimiseBills told me it was not the cheapest and that I might have been mis-sold.  Ian lodged a formal complaint on my behalf, and from a recording of the phone call got the supplier to accept mis-selling and recalculate my bills.  I'm now £300 in credit and have £50 compensation on top!  I'm very happy."     Mr and Mrs Buyers, Newcastle upon Tyne
“Ian checked my energy bill and spotted an error made by the supplier – charging me a higher rate than I’d originally signed up for.  They recalculated my bills and I got an extra £70 credited to my account!”   Mr P. Smyth, London.  
No other price comparison service will give you this level of support and attention.  Not only do you pay less for your energy year after year, we are available on the end of a phone (no call centre!) to help with your energy bills. 
The illustration below is based on the last information we had for you.  If it's out of date, please go to https://optimisebills.com/Account/Usage.aspx to update your details, or provide your latest supplier, tariff and usage £ or kwh in this email - with your S20 8GW if you've moved house. 
Or just give me a call on 0345 130 3858.
Or request a callback (please provide your phone number). 
  
Compare Now
Kind regards
Ian
OptimiseBills
0845 130 3858
 
You have received this e-mail as you have registered an enquiry with OptimiseBills. By unsubscribing we will not be able to contact you with details of money saving opportunities in the future. To unsubscribe, reply with “unsubscribe” in the subject.

**Comment by iddmaxwell** [comment]
I forgot that I'm out tonight at a concert so can't do a call. Can we do Thursday?  
Have you looked at this issue?  Hopefully easy to sort.

**Comment by Will-Newton** [comment]
Fixed
