### ISSUE TITLE
PRIORITY 1: Calculate button is not working on some energy records

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#86]
e.g. see Eric Howell
https://optimisebills.com/Admin/EnergyRecordEditor.aspx?RecordNum=HOW003-04C
There are rates for the current tariff but pressing 'calculate' does nothing. 

Console shows this: 
HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://optimisebills.com/Admin/EnergyRecordEditor.aspx?RecordNum=HOW003-04C
SCRIPT5022: Sys.WebForms.PageRequestManagerServerErrorException: An unknown error occurred while processing the request on the server. The status code returned from the server was: 500
ScriptResource.axd (939,13)

**Comment by iddmaxwell** [comment]
cannot update clients' energy records. A related issue is that I cannot set Tom Wrenn's record to the correct tariff because it's no longer available - and because of this issue too. It should be Scottish Power fixed June 2018. I've had to set it to April 2018 because I don't have anything else in the api feed.

**Comment by Will-Newton** [comment]
Fixed
