### ISSUE TITLE
PRIORITY 1: i've overwritten Kieran O'Mahoney with Max Howard's details. 

### ISSUE THREAD

**Issue by iddmaxwell** [iddmaxwell/optimisebills#97]
Can you restore Kieran's details to his record?  

I had a tab open and pressed 'save' so it overwrote everything.

**Comment by Will-Newton** [comment]
Think it's ok now. Please take a look.

**Comment by iddmaxwell** [comment]
I've had a look - it doesn't look right.  Search for Mahoney doesn't pull up his record for example.

**Comment by Will-Newton** [comment]
Do you know what the email address was like?

**Comment by iddmaxwell** [comment]
kieranomahoney@yahoo.co.uk
This email address is in the database.

**Comment by iddmaxwell** [comment]
Any idea why I can no longer assign GitHub issues?  Or label them?

**Comment by Will-Newton** [comment]
Fixed now?

**Comment by iddmaxwell** [comment]
GitHub have fixed their issue. The data looks fine again.
